#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name:
  en: A.D Adams
  ar: عبدالرحمن ادم
# Site settings
title:
  en: Personal Website
  ar: الموقع الشخصي
email: adams100111@gmail.com
# Short bio or description (displayed in the header)
description:
  en: Software Designer & Developer
  ar: مصمم ومطور برمجيات
subtitle:
  en: Designer & Developer
  ar: مصمم و مطور
index:
  en:
  ar: index-ar.html
feed:
  en: /feed.xml
  ar: /feed-ar.xml
# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://raw.githubusercontent.com/adams100111/src/master/resume-profile.jpg

#
# Flags below are optional
#

# navbar items

navbar:
  en:
    home: 
      title: home
      url: /
    cv: 
      title: cv
      url: /cv/
    blog: 
      title: blog
      url: /blog/
    portfolio: 
      title: portfolio
      url: /portfolio/

  ar:
    home: 
      title: الرئيسية
      url: /ar/
    cv: 
      title: عنـــي
      url: /ar/cv/
    blog: 
      title: المدونة
      url: /ar/blog/
    portfolio: 
      title: اعمالـــي
      url: /ar/portfolio/
blog:
  personal-website:
    en: /
    ar: /ar
  url:
    en: /blog
    ar: /ar/blog
  read:
    en: Also read
    ar: اقرأ ايضا
  about:
    en: 
      title: About me
      url: /about
    ar: 
      title: عنـــي
      url: /ar/about
  skills:
    en: Designer & Developer
    ar: مصمم ومطور
  skills:
    en: category
    ar: مصمم ومطور
# Includes an icon in the social for each username you enter
social-links:
  email: adams100111@gmail.com
  facebook: adams100111
  github: adams100111
  instagram: adams100111
  linkedin: adams100111
  rss: true
  twitter: adams100111
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: adams100111


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: adams100111

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: (http://adams100111.github.io/adams100111)

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

assets: ''

repository: adams100111/adams100111.github.io


permalink: /:title/

# The release of Jekyll Now that you're using
version: v3.6.2

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
timezone: Africa/Cairo
# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
